### ISSUE TITLE
予約一覧表示部分をスクロール可能なエリアに改善する

### ISSUE THREAD

**Issue by ak-kitsuda** [ak-kitsuda/meeting-room-reservation-prod#1]
## 概要
現在の予約一覧表示部分は、予約件数が増えると縦に長くなり、ページ全体のスクロールが必要になります。予約一覧のみをスクロール可能なエリア内に表示することで、ユーザビリティを向上させる必要があります。

## 現状の問題点
- 予約件数が増えるとページが縦に長くなり、全体的なUIが使いづらくなる
- 他の機能にアクセスするためにページ全体をスクロールする必要がある
- モバイル端末での操作性が特に悪化する

## 改善案
1. 予約一覧の表示エリア（`#reservations-list`）に固定高さを設定し、スクロール可能にする
2. 最大高さを設定し、それを超える場合はスクロールバーを表示する
3. スクロールバーのデザインをモダンで使いやすいものにする

### CSSの変更点
```css
#reservations-list {
    max-height: 500px; /* 適切な高さに調整 */
    overflow-y: auto; /* 縦方向のスクロールを有効化 */
    padding-right: 10px; /* スクロールバー分の余白 */
}

/* スクロールバーのカスタマイズ (Webkit系ブラウザ) */
#reservations-list::-webkit-scrollbar {
    width: 8px;
}

#reservations-list::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 4px;
}

#reservations-list::-webkit-scrollbar-thumb {
    background: var(--primary-light);
    border-radius: 4px;
}

#reservations-list::-webkit-scrollbar-thumb:hover {
    background: var(--primary-color);
}
```

### レスポンシブ対応
```css
@media (max-width: 768px) {
    #reservations-list {
        max-height: 400px; /* モバイル向けに高さを調整 */
    }
}
```

## 期待される効果
- ページ全体の使いやすさの向上
- 予約一覧の視認性アップ
- 特に予約件数が多い場合のユーザービリティ改善
- モバイル端末での操作性向上

## 関連ファイル
- `meeting-room-reservation/css/styles.css`
- `meeting-room-reservation/index.html`

## 優先度
中 - ユーザビリティ向上のために重要な改善
